services:
  node:
    image: node:alpine
    working_dir: /app
    command: /bin/sh -c "yarn && yarn start"
    volumes:
      - .:/app:delegated
      - /app/node_modules
    ports:
      - 8085:8080

  # Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 1888:1888 # pprof extension
      # - 8888:8888 # Prometheus metrics exposed by the collector
      # - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      # - 4317:4317 # OTLP gRPC receiver
      # - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension

  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:1.48
    ports:
      - "16686:16686"
      - "14268:14268"
      - "14250"